apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-web
  labels:
    app: status-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: status-web
  template:
    metadata:
      labels:
        app: status-web
    spec:
      containers:
      - name: status-web
        image: registry.ng.bluemix.net/status_page/web:1
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: "redis-leader"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: status-web
  labels:
    app: status-web
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    name: status-web
    protocol: TCP
  selector:
    app: status-web
